[package]
name = "converter"
version = "0.1.0"
edition = "2024"

[dependencies]
bank_account_parser = { path = "../bank_account_parser" }
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }

